import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";

const commissioner = localFont({
  src: "../../public/Commissioner-VariableFont.ttf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${commissioner.className} antialiased bg-blue_dark`}>
          <Header />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
